name: Python application
run-name: test 

on:
  push:
    branches: [ main ]
  workflow_call:
    secrets:
      SECRET_KEY:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysqldb:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 'navi'
          MYSQL_DATABASE: 'test_db'
        ports:
          - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        
    steps:
    - name: 'Create env file'
      run: |
        touch .env
        echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
        echo KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        cat .env

    - run: echo "🎉 The job was automatically triggered by a ${{ secrets.DB_NAME }} event."

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/requirements.test.txt
        
    - name: Start Pytest
      run: |
        pytest

