name: Python application
run-name: test 

on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    # services:
    #   mysqldb:
    #     image: mysql:latest
    #     env:
    #       MYSQL_USER: ${{DB_USER}}
    #       MYSQL_PASSWORD: ${{DB_PASSWORD}}
    #       MYSQL_DATABASE: ${{DB_NAME}}
    #       MYSQL_ROOT_PASSWORD: ${{DB_PASSWORD}} 
    #     ports:
    #       - 3306:3306 
    #     options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/checkout@v4
 
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: ["3.9", "3.10", "3.11"]
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Start Pytest
      run: |
        pytest

