name: Python application
run-name: test 

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    services:
      mysqldb:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 'navi'
          MYSQL_DATABASE: 'test_db'
        ports:
          - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.SECRET_KEY }}

    - name: 'Create env file'
      run: |
        touch .env
        echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
        echo KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY }} >> .env
        echo DB_NAME=test_db >> .env
        echo DB_HOST=127.0.0.1 >> .env
        echo DB_PORT=3306 >> .env
        echo DB_PASSWORD=navi >> .env
        echo DB_USER=root >> .env
        cat .env

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/requirements.test.txt
        
    - name: Start Pytest
      run: |
        pytest

