name: Python application
run-name: test 

on:
  push:
    branches: [ main ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysqldb:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ vars.DB_PASSWORD }}
          MYSQL_USER: ${{ vars.DB_USER }}
          MYSQL_PASSWORD: ${{ vars.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ vars.DB_NAME }}
        ports:
          - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
        
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - uses: actions/checkout@v4
 
    - name: 'Create env file'
      run: |
        touch .env
        echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
        echo KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY }} >> .env
        echo DB_NAME=${{ vars.DB_NAME }} >> .env
        echo DB_HOST=${{ vars.DB_HOST }} >> .env
        echo DB_PORT=${{ vars.DB_PORT }} >> .env
        echo DB_PASSWORD=${{ vars.DB_PASSWORD }} >> .env
        echo DB_USER=${{ vars.DB_USER }} >> .env
        cat .env

    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./requirements/requirements.test.txt
        
    - name: Start Pytest
      run: |
        pytest

